"""empty message

Revision ID: 64094930ea02
Revises: 
Create Date: 2018-05-27 17:13:08.595552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64094930ea02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actor_bio'), 'actor', ['bio'], unique=False)
    op.create_index(op.f('ix_actor_dob'), 'actor', ['dob'], unique=False)
    op.create_index(op.f('ix_actor_id'), 'actor', ['id'], unique=False)
    op.create_index(op.f('ix_actor_name'), 'actor', ['name'], unique=False)
    op.create_index(op.f('ix_actor_sex'), 'actor', ['sex'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actor_sex'), table_name='actor')
    op.drop_index(op.f('ix_actor_name'), table_name='actor')
    op.drop_index(op.f('ix_actor_id'), table_name='actor')
    op.drop_index(op.f('ix_actor_dob'), table_name='actor')
    op.drop_index(op.f('ix_actor_bio'), table_name='actor')
    op.drop_table('actor')
    # ### end Alembic commands ###
