"""empty message

Revision ID: 9d23a76c6da7
Revises: 64094930ea02
Create Date: 2018-05-28 08:52:53.997742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d23a76c6da7'
down_revision = '64094930ea02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producer_bio'), 'producer', ['bio'], unique=False)
    op.create_index(op.f('ix_producer_dob'), 'producer', ['dob'], unique=False)
    op.create_index(op.f('ix_producer_id'), 'producer', ['id'], unique=False)
    op.create_index(op.f('ix_producer_name'), 'producer', ['name'], unique=False)
    op.create_index(op.f('ix_producer_sex'), 'producer', ['sex'], unique=False)
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year_of_release', sa.String(), nullable=False),
    sa.Column('plot', sa.String(), nullable=False),
    sa.Column('poster', sa.LargeBinary(), nullable=False),
    sa.Column('producer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producer_id'], ['producer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_id'), 'movie', ['id'], unique=False)
    op.create_index(op.f('ix_movie_name'), 'movie', ['name'], unique=False)
    op.create_index(op.f('ix_movie_plot'), 'movie', ['plot'], unique=False)
    op.create_index(op.f('ix_movie_poster'), 'movie', ['poster'], unique=False)
    op.create_index(op.f('ix_movie_year_of_release'), 'movie', ['year_of_release'], unique=False)
    op.create_table('cast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cast_id'), 'cast', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cast_id'), table_name='cast')
    op.drop_table('cast')
    op.drop_index(op.f('ix_movie_year_of_release'), table_name='movie')
    op.drop_index(op.f('ix_movie_poster'), table_name='movie')
    op.drop_index(op.f('ix_movie_plot'), table_name='movie')
    op.drop_index(op.f('ix_movie_name'), table_name='movie')
    op.drop_index(op.f('ix_movie_id'), table_name='movie')
    op.drop_table('movie')
    op.drop_index(op.f('ix_producer_sex'), table_name='producer')
    op.drop_index(op.f('ix_producer_name'), table_name='producer')
    op.drop_index(op.f('ix_producer_id'), table_name='producer')
    op.drop_index(op.f('ix_producer_dob'), table_name='producer')
    op.drop_index(op.f('ix_producer_bio'), table_name='producer')
    op.drop_table('producer')
    # ### end Alembic commands ###
