"""empty message

Revision ID: f926ace60b35
Revises: 9d23a76c6da7
Create Date: 2018-07-02 21:36:00.387990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f926ace60b35'
down_revision = '9d23a76c6da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('poster', sa.String(), nullable=True))
    op.create_index(op.f('ix_actor_poster'), 'actor', ['poster'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actor_poster'), table_name='actor')
    op.drop_column('actor', 'poster')
    # ### end Alembic commands ###
